-- ============================================================
-- OSFishing — CONSOLIDATED SCHEMA
-- ============================================================
-- Complete database structure and seed content in one file.
-- Generated by replaying all migrations in dependency order and
-- dumping the verified result.
--
-- To build a fresh database:
--     mysql -u <user> -p <database> < schema.sql
--
-- This supersedes replaying the individual *_migration.sql files,
-- which are retained as history. Three of them do not replay cleanly
-- against a fresh database and were corrected while producing this file:
--
--   * admin_migration.sql       re-adds players.is_admin, already in the
--                               base schema (applied here as idempotent)
--   * butcher_migration.sql     used columns fish_species_id/affinity_weight
--                               (real names: fish_id/affinity) and joined a
--                               table, fish_spot_availability, that does not
--                               exist; rewritten against fish_water_types
--   * missing_columns_migration.sql
--                               NEW — adds quests.quest_group, quests.quest_tier
--                               and bait_types.min_level, which were added
--                               directly to the old live database and never
--                               captured in any committed migration
--
-- Order also matters: quest_data.sql inserts explicit quest ids 1-12 and must
-- run before repeatable_quest_migration.sql, which relies on auto-increment.
--
-- Contains no player data. Register the first account through the web portal.
--
-- Known pre-existing issue, NOT fixed here: includes/Tournament.php queries
-- columns (name, metric, spot_id, region_name, grid_name, start_time,
-- end_time, status, created_by) that do not match the tournaments table
-- (title, scoring_type, starts_at, ends_at, ...). Tracked in CLAUDE.md.
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;
DROP TABLE IF EXISTS `announcements`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `announcements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `message` text NOT NULL,
  `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  `starts_at` datetime NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `announcements_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `players` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `announcements` DISABLE KEYS */;
/*!40000 ALTER TABLE `announcements` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `bait_gather_points`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bait_gather_points` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `bait_id` int(10) unsigned NOT NULL,
  `player_id` int(10) unsigned DEFAULT NULL,
  `region_name` varchar(64) DEFAULT NULL,
  `pos_x` float DEFAULT NULL,
  `pos_y` float DEFAULT NULL,
  `pos_z` float DEFAULT NULL,
  `max_stock` int(10) unsigned NOT NULL DEFAULT 25,
  `current_stock` int(10) unsigned NOT NULL DEFAULT 25,
  `last_depleted` datetime DEFAULT NULL,
  `last_regen` datetime DEFAULT NULL,
  `respawn_minutes` int(10) unsigned NOT NULL DEFAULT 30,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `bait_id` (`bait_id`),
  KEY `player_id` (`player_id`),
  CONSTRAINT `bait_gather_points_ibfk_1` FOREIGN KEY (`bait_id`) REFERENCES `bait_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `bait_gather_points_ibfk_2` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `bait_gather_points` DISABLE KEYS */;
/*!40000 ALTER TABLE `bait_gather_points` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `bait_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `bait_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` text DEFAULT NULL,
  `gather_location` varchar(256) DEFAULT NULL,
  `gather_method` varchar(128) DEFAULT NULL,
  `shop_price` int(10) unsigned DEFAULT NULL,
  `shop_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `shop_quantity` int(10) unsigned DEFAULT 10,
  `gather_min` int(10) unsigned NOT NULL DEFAULT 1,
  `gather_max` int(10) unsigned NOT NULL DEFAULT 3,
  `gather_cooldown` int(10) unsigned NOT NULL DEFAULT 30,
  `catch_rate_mod` float NOT NULL DEFAULT 1,
  `rarity_mod` float NOT NULL DEFAULT 1,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `icon_texture` varchar(36) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `bait_types` DISABLE KEYS */;
INSERT INTO `bait_types` (`id`, `name`, `description`, `gather_location`, `gather_method`, `shop_price`, `shop_enabled`, `shop_quantity`, `gather_min`, `gather_max`, `gather_cooldown`, `catch_rate_mod`, `rarity_mod`, `min_level`, `icon_texture`, `is_active`, `created_at`) VALUES (1,'Earthworms','Versatile all-purpose freshwater bait.','Compost pile / muddy garden','Click dirt mound, digging animation',5,1,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:33'),
(2,'Grasshoppers','Great for surface feeders. Tricky to catch.','Tall grass meadow','Click grass clumps, snatching animation',10,1,NULL,1,2,25,1.1,1,1,NULL,1,'2026-09-14 18:28:33'),
(3,'Crickets','Best at evening and night. Good freshwater bait.','Under rocks/logs in wooded area','Click rock/log to flip and collect',10,1,NULL,1,3,30,1.1,1,1,NULL,1,'2026-09-14 18:28:33'),
(4,'Minnows','Live bait for larger predatory fish.','Shallow stream / tide pool','Click net object to scoop',8,1,NULL,1,2,45,1.2,1.1,1,NULL,1,'2026-09-14 18:28:33'),
(5,'Cut Bait','Chunks of fish. Strong for catfish and ocean.','Bait preparation table','Bring a caught fish, click table to cut',18,1,NULL,2,5,0,1.2,1.1,1,NULL,1,'2026-09-14 18:28:33'),
(6,'Leeches','Premium freshwater bait. Great for deep water.','Swampy bog area','Click submerged rocks/logs in swamp',12,1,NULL,1,2,60,1.3,1.3,1,NULL,1,'2026-09-14 18:28:33'),
(7,'Corn Kernels','Cheap bulk bait. Carp love it.','Farm stand / corn field','Click corn stalks or bushel basket',5,1,10,2,5,20,0.9,0.8,1,NULL,1,'2026-09-14 18:28:33'),
(8,'Shrimp','Essential saltwater bait. Good for ocean fish.','Coastal tidal flat / dock','Click shrimp trap or dip net at waters edge',15,1,NULL,1,3,45,1.2,1.1,1,NULL,1,'2026-09-14 18:28:33'),
(9,'Bread Dough','Basic starter bait. Easy to get.','Bakery / kitchen area','Click table with bread to ball up dough',8,1,10,3,6,15,0.8,0.7,1,NULL,1,'2026-09-14 18:28:33'),
(10,'Glow Grubs','Rare luminous grubs. Key to legendary catches.','Cave / underground area','Click glowing spots on walls or under rocks',10,0,NULL,1,1,300,1.5,2.5,1,NULL,1,'2026-09-14 18:28:33'),
(11,'Fish Chunks','Chopped fish pieces. Predators love them.',NULL,NULL,0,0,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:34'),
(12,'Shimmering Minnow','A tiny iridescent minnow found inside a pond fish. Irresistible to legendary pond dwellers.',NULL,NULL,NULL,0,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:34'),
(13,'River Pearl','A lustrous pearl formed inside a river fish. Legendary river fish can\'t resist.',NULL,NULL,NULL,0,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:34'),
(14,'Deep Lake Grub','A fat luminous grub from a lake fish\'s belly. Lures legendary lake monsters.',NULL,NULL,NULL,0,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:34'),
(15,'Abyssal Eye','A glowing eye from a deep-sea predator. Draws legendary ocean beasts.',NULL,NULL,NULL,0,10,1,3,30,1,1,1,NULL,1,'2026-09-14 18:28:34'),
(16,'Magnet','A powerful magnet on a line. Attracts junk from the water but fish hate it. Level 8+.',NULL,NULL,300,0,5,1,3,30,0.3,0.1,8,NULL,1,'2026-09-14 18:28:34');
/*!40000 ALTER TABLE `bait_types` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `buff_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `buff_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `buff_type` varchar(32) NOT NULL,
  `effect_value` float NOT NULL DEFAULT 0.25,
  `duration_mins` int(10) unsigned NOT NULL DEFAULT 30,
  `description` text DEFAULT NULL,
  `source` enum('craft','quest','shop','admin') NOT NULL DEFAULT 'shop',
  `shop_price` int(10) unsigned DEFAULT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `buff_items` DISABLE KEYS */;
INSERT INTO `buff_items` (`id`, `name`, `buff_type`, `effect_value`, `duration_mins`, `description`, `source`, `shop_price`, `min_level`, `is_active`, `created_at`) VALUES (1,'Chum Bucket','chum',0.25,30,'+25% bite chance. Craft from 2 rare fish at the butchering table.','craft',NULL,5,1,'2026-09-14 18:28:33'),
(2,'Lucky Lure Oil','lure_oil',0.15,20,'+15% rare fish chance. Craft from 1 legendary fish.','craft',NULL,5,1,'2026-09-14 18:28:33'),
(3,'Growth Tonic','growth',0.2,30,'+20% fish weight. Earned from quests.','quest',NULL,4,1,'2026-09-14 18:28:33'),
(4,'Angler\'s Blessing','blessing',0.25,30,'+25% XP gain. Earned from quests.','quest',NULL,4,1,'2026-09-14 18:28:33'),
(5,'Treasure Scent','treasure',0.5,20,'+50% junk item chance. Earned from quests.','quest',NULL,4,1,'2026-09-14 18:28:33'),
(6,'Calm Waters','calm',0.2,20,'-20% fight difficulty. Buy from the shop.','shop',200,3,1,'2026-09-14 18:28:33'),
(7,'Bait Saver','bait_saver',0.25,30,'25% chance bait not consumed. Buy from the shop.','shop',250,3,1,'2026-09-14 18:28:33'),
(8,'Double Hook','double_hook',0.3,15,'30% chance double catch. Admin reward only.','admin',NULL,1,1,'2026-09-14 18:28:33'),
(9,'Golden Hour','golden_hour',0.1,15,'+10% to everything. Admin reward only.','admin',NULL,1,1,'2026-09-14 18:28:33');
/*!40000 ALTER TABLE `buff_items` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `catch_log`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `catch_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `fish_species_id` int(10) unsigned NOT NULL,
  `weight` float NOT NULL,
  `rarity_id` int(10) unsigned NOT NULL,
  `spot_id` int(10) unsigned DEFAULT NULL,
  `bait_used_id` int(10) unsigned DEFAULT NULL,
  `rod_used_id` int(10) unsigned DEFAULT NULL,
  `cast_distance` float DEFAULT NULL,
  `fight_duration` int(10) unsigned DEFAULT NULL,
  `xp_awarded` int(10) unsigned NOT NULL DEFAULT 0,
  `caught_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `rarity_id` (`rarity_id`),
  KEY `idx_player` (`player_id`),
  KEY `idx_species` (`fish_species_id`),
  KEY `idx_caught_at` (`caught_at`),
  KEY `idx_leaderboard` (`fish_species_id`,`weight` DESC),
  CONSTRAINT `catch_log_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `catch_log_ibfk_2` FOREIGN KEY (`fish_species_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `catch_log_ibfk_3` FOREIGN KEY (`rarity_id`) REFERENCES `rarity_tiers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `catch_log` DISABLE KEYS */;
/*!40000 ALTER TABLE `catch_log` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `daily_purchase_limits`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `daily_purchase_limits` (
  `player_id` int(10) unsigned NOT NULL,
  `purchase_date` date NOT NULL,
  `web_purchases` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`player_id`,`purchase_date`),
  CONSTRAINT `daily_purchase_limits_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `daily_purchase_limits` DISABLE KEYS */;
/*!40000 ALTER TABLE `daily_purchase_limits` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `faq_entries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `faq_entries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `question` varchar(512) NOT NULL,
  `answer` text NOT NULL,
  `category` varchar(64) DEFAULT 'general',
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `faq_entries` DISABLE KEYS */;
/*!40000 ALTER TABLE `faq_entries` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `fish_bait_affinity`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fish_bait_affinity` (
  `fish_id` int(10) unsigned NOT NULL,
  `bait_id` int(10) unsigned NOT NULL,
  `affinity` float NOT NULL DEFAULT 1,
  `is_required` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`fish_id`,`bait_id`),
  KEY `bait_id` (`bait_id`),
  CONSTRAINT `fish_bait_affinity_ibfk_1` FOREIGN KEY (`fish_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `fish_bait_affinity_ibfk_2` FOREIGN KEY (`bait_id`) REFERENCES `bait_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `fish_bait_affinity` DISABLE KEYS */;
INSERT INTO `fish_bait_affinity` (`fish_id`, `bait_id`, `affinity`, `is_required`) VALUES (1,1,2,0),
(1,2,1.2,0),
(1,3,1.5,0),
(1,4,0.5,0),
(1,5,0.3,0),
(1,6,0.8,0),
(1,7,1,0),
(1,8,0.3,0),
(1,9,1.2,0),
(1,10,0.5,0),
(1,11,1,0),
(1,12,2,0),
(1,16,0.05,0),
(2,1,2,0),
(2,2,1,0),
(2,3,1.2,0),
(2,4,0.5,0),
(2,5,0.3,0),
(2,6,0.8,0),
(2,7,1,0),
(2,8,0.3,0),
(2,9,1.5,0),
(2,10,0.5,0),
(2,11,1,0),
(2,12,2,0),
(2,16,0.05,0),
(3,1,1.5,0),
(3,2,0.3,0),
(3,3,0.5,0),
(3,4,0.8,0),
(3,5,2,0),
(3,6,1.2,0),
(3,7,0.8,0),
(3,8,0.8,0),
(3,9,1,0),
(3,10,1,0),
(3,11,1,0),
(3,12,2,0),
(3,16,0.05,0),
(4,1,1,0),
(4,2,0.5,0),
(4,3,0.8,0),
(4,4,0.3,0),
(4,5,0.3,0),
(4,6,0.5,0),
(4,7,1.5,0),
(4,8,0.3,0),
(4,9,2,0),
(4,10,0.5,0),
(4,11,1,0),
(4,12,2,0),
(4,16,0.05,0),
(5,1,1.2,0),
(5,2,1,0),
(5,3,0.8,0),
(5,4,2,0),
(5,5,1,0),
(5,6,1.5,0),
(5,7,0.3,0),
(5,8,0.5,0),
(5,9,0.3,0),
(5,10,0.8,0),
(5,11,3,0),
(5,12,2,0),
(5,16,0.05,0),
(6,1,1,0),
(6,2,0.5,0),
(6,3,0.5,0),
(6,4,1.5,0),
(6,5,2,0),
(6,6,1,0),
(6,7,0.3,0),
(6,8,0.8,0),
(6,9,0.3,0),
(6,10,0.5,0),
(6,11,1,0),
(6,12,2,0),
(6,16,0.05,0),
(7,1,0.8,0),
(7,2,0.3,0),
(7,3,0.5,0),
(7,4,0.3,0),
(7,5,0.3,0),
(7,6,0.3,0),
(7,7,1.2,0),
(7,8,0.3,0),
(7,9,1.5,0),
(7,10,2,0),
(7,11,1,0),
(7,12,10,0),
(7,16,0.05,0),
(8,1,2,0),
(8,2,1,0),
(8,3,1.2,0),
(8,4,0.5,0),
(8,5,0.3,0),
(8,6,0.8,0),
(8,7,0.8,0),
(8,8,0.3,0),
(8,9,1,0),
(8,10,0.5,0),
(8,11,1,0),
(8,13,2,0),
(8,16,0.05,0),
(9,1,1.2,0),
(9,2,2,0),
(9,3,1.5,0),
(9,4,1,0),
(9,5,0.5,0),
(9,6,0.8,0),
(9,7,0.3,0),
(9,8,0.5,0),
(9,9,0.3,0),
(9,10,0.8,0),
(9,11,1,0),
(9,13,2,0),
(9,16,0.05,0),
(10,1,1.2,0),
(10,2,1.5,0),
(10,3,1,0),
(10,4,2,0),
(10,5,0.8,0),
(10,6,1,0),
(10,7,0.3,0),
(10,8,0.5,0),
(10,9,0.3,0),
(10,10,0.8,0),
(10,11,1,0),
(10,13,2,0),
(10,16,0.05,0),
(11,1,1.2,0),
(11,2,1,0),
(11,3,1,0),
(11,4,1.5,0),
(11,5,0.8,0),
(11,6,2,0),
(11,7,0.3,0),
(11,8,0.5,0),
(11,9,0.3,0),
(11,10,0.8,0),
(11,11,1,0),
(11,13,2,0),
(11,16,0.05,0),
(12,1,1,0),
(12,2,0.5,0),
(12,3,0.8,0),
(12,4,2,0),
(12,5,1,0),
(12,6,1.5,0),
(12,7,0.3,0),
(12,8,0.5,0),
(12,9,0.3,0),
(12,10,1.2,0),
(12,11,3,0),
(12,13,2,0),
(12,16,0.05,0),
(13,1,0.8,0),
(13,2,0.5,0),
(13,3,0.5,0),
(13,4,1.2,0),
(13,5,1.5,0),
(13,6,0.8,0),
(13,7,0.3,0),
(13,8,2,0),
(13,9,0.3,0),
(13,10,1,0),
(13,11,2,0),
(13,13,2,0),
(13,16,0.05,0),
(14,1,1.5,0),
(14,2,0.3,0),
(14,3,0.5,0),
(14,4,0.8,0),
(14,5,2,0),
(14,6,1.2,0),
(14,7,0.5,0),
(14,8,1,0),
(14,9,0.3,0),
(14,10,1.5,0),
(14,11,1,0),
(14,13,5,0),
(14,16,0.05,0),
(15,1,0.8,0),
(15,2,0.3,0),
(15,3,0.3,0),
(15,4,0.8,0),
(15,5,1.2,0),
(15,6,1,0),
(15,7,0.3,0),
(15,8,0.5,0),
(15,9,0.3,0),
(15,10,2,0),
(15,11,1,0),
(15,13,10,0),
(15,16,0.05,0),
(16,1,2,0),
(16,2,0.8,0),
(16,3,1,0),
(16,4,1.5,0),
(16,5,0.5,0),
(16,6,0.8,0),
(16,7,0.3,0),
(16,8,0.5,0),
(16,9,0.5,0),
(16,10,0.5,0),
(16,11,2,0),
(16,14,2,0),
(16,16,0.05,0),
(17,1,1.2,0),
(17,2,1,0),
(17,3,1.5,0),
(17,4,2,0),
(17,5,0.5,0),
(17,6,0.8,0),
(17,7,0.3,0),
(17,8,0.5,0),
(17,9,0.3,0),
(17,10,0.8,0),
(17,11,1,0),
(17,14,2,0),
(17,16,0.05,0),
(18,1,1.5,0),
(18,2,0.3,0),
(18,3,0.5,0),
(18,4,0.8,0),
(18,5,2,0),
(18,6,1.2,0),
(18,7,0.5,0),
(18,8,1,0),
(18,9,0.8,0),
(18,10,1,0),
(18,11,1,0),
(18,14,2,0),
(18,16,0.05,0),
(19,1,1,0),
(19,2,0.8,0),
(19,3,0.8,0),
(19,4,2,0),
(19,5,1,0),
(19,6,1.5,0),
(19,7,0.3,0),
(19,8,0.5,0),
(19,9,0.3,0),
(19,10,0.8,0),
(19,11,1,0),
(19,14,2,0),
(19,16,0.05,0),
(20,1,1.2,0),
(20,2,0.3,0),
(20,3,0.5,0),
(20,4,0.3,0),
(20,5,0.3,0),
(20,6,0.8,0),
(20,7,2,0),
(20,8,0.3,0),
(20,9,2,0),
(20,10,0.5,0),
(20,11,2,0),
(20,14,2,0),
(20,16,0.05,0),
(21,1,0.8,0),
(21,2,0.5,0),
(21,3,0.5,0),
(21,4,2,0),
(21,5,1.5,0),
(21,6,1.2,0),
(21,7,0.3,0),
(21,8,0.8,0),
(21,9,0.3,0),
(21,10,1,0),
(21,11,3,0),
(21,14,2,0),
(21,16,0.05,0),
(22,1,0.8,0),
(22,2,0.3,0),
(22,3,0.5,0),
(22,4,2,0),
(22,5,1.2,0),
(22,6,1,0),
(22,7,0.3,0),
(22,8,1.5,0),
(22,9,0.3,0),
(22,10,1.5,0),
(22,11,1,0),
(22,14,2,0),
(22,16,0.05,0),
(23,1,0.5,0),
(23,2,0.3,0),
(23,3,0.3,0),
(23,4,2,0),
(23,5,2,0),
(23,6,1.2,0),
(23,7,0.3,0),
(23,8,1,0),
(23,9,0.3,0),
(23,10,1.2,0),
(23,11,3,0),
(23,14,5,0),
(23,16,0.05,0),
(24,1,0.3,0),
(24,2,0.3,0),
(24,3,0.3,0),
(24,4,1.5,0),
(24,5,1.5,0),
(24,6,1,0),
(24,7,0.3,0),
(24,8,0.8,0),
(24,9,0.3,0),
(24,10,2,0),
(24,11,1,0),
(24,14,10,0),
(24,16,0.05,0),
(25,1,0.5,0),
(25,2,0.3,0),
(25,3,0.3,0),
(25,4,1.2,0),
(25,5,1.5,0),
(25,6,0.5,0),
(25,7,0.3,0),
(25,8,2,0),
(25,9,0.3,0),
(25,10,0.8,0),
(25,11,1,0),
(25,15,2,0),
(25,16,0.05,0),
(26,1,0.5,0),
(26,2,0.3,0),
(26,3,0.3,0),
(26,4,1,0),
(26,5,1.5,0),
(26,6,0.8,0),
(26,7,0.3,0),
(26,8,2,0),
(26,9,0.3,0),
(26,10,0.8,0),
(26,11,1,0),
(26,15,2,0),
(26,16,0.05,0),
(27,1,0.8,0),
(27,2,0.3,0),
(27,3,0.3,0),
(27,4,1,0),
(27,5,2,0),
(27,6,0.5,0),
(27,7,0.3,0),
(27,8,1.5,0),
(27,9,0.3,0),
(27,10,0.8,0),
(27,11,1,0),
(27,15,2,0),
(27,16,0.05,0),
(28,1,0.5,0),
(28,2,0.3,0),
(28,3,0.3,0),
(28,4,1.2,0),
(28,5,1.5,0),
(28,6,0.8,0),
(28,7,0.3,0),
(28,8,2,0),
(28,9,0.3,0),
(28,10,1,0),
(28,11,1,0),
(28,15,2,0),
(28,16,0.05,0),
(29,1,0.3,0),
(29,2,0.3,0),
(29,3,0.3,0),
(29,4,1.5,0),
(29,5,2,0),
(29,6,0.5,0),
(29,7,0.3,0),
(29,8,1.2,0),
(29,9,0.3,0),
(29,10,1,0),
(29,11,1,0),
(29,15,2,0),
(29,16,0.05,0),
(30,1,0.3,0),
(30,2,0.3,0),
(30,3,0.3,0),
(30,4,2,0),
(30,5,1.5,0),
(30,6,0.5,0),
(30,7,0.3,0),
(30,8,1,0),
(30,9,0.3,0),
(30,10,0.8,0),
(30,11,3,0),
(30,15,2,0),
(30,16,0.05,0),
(31,1,0.3,0),
(31,2,0.3,0),
(31,3,0.3,0),
(31,4,1,0),
(31,5,2,0),
(31,6,0.5,0),
(31,7,0.3,0),
(31,8,1.2,0),
(31,9,0.3,0),
(31,10,1.5,0),
(31,11,3,0),
(31,15,5,0),
(31,16,0.05,0),
(32,1,0.3,0),
(32,2,0.3,0),
(32,3,0.3,0),
(32,4,1.5,0),
(32,5,2,0),
(32,6,0.8,0),
(32,7,0.3,0),
(32,8,1.2,0),
(32,9,0.3,0),
(32,10,1,0),
(32,11,1,0),
(32,15,5,0),
(32,16,0.05,0),
(33,1,0.3,0),
(33,2,0.3,0),
(33,3,0.3,0),
(33,4,1.2,0),
(33,5,2,0),
(33,6,0.5,0),
(33,7,0.3,0),
(33,8,1,0),
(33,9,0.3,0),
(33,10,2,0),
(33,11,1,0),
(33,15,10,0),
(33,16,0.05,0),
(34,1,0.3,0),
(34,2,0.3,0),
(34,3,0.3,0),
(34,4,0.3,0),
(34,5,0.3,0),
(34,6,0.3,0),
(34,7,0.3,0),
(34,8,0.5,0),
(34,9,0.3,0),
(34,10,2,0),
(34,11,1,0),
(34,15,10,0),
(34,16,0.05,0),
(35,1,2,0),
(35,2,0.3,0),
(35,3,0.5,0),
(35,4,0.8,0),
(35,5,1,0),
(35,6,1.2,0),
(35,7,0.3,0),
(35,8,0.8,0),
(35,9,0.3,0),
(35,10,1.5,0),
(35,11,2,0),
(35,13,2,0),
(35,14,2,0),
(35,16,0.05,0);
/*!40000 ALTER TABLE `fish_bait_affinity` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `fish_species`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fish_species` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `rarity_id` int(10) unsigned NOT NULL,
  `min_weight` float NOT NULL,
  `max_weight` float NOT NULL,
  `line_tolerance` float NOT NULL DEFAULT 5,
  `base_points` int(10) unsigned NOT NULL,
  `description` text DEFAULT NULL,
  `fight_stamina` float NOT NULL DEFAULT 50,
  `fight_speed` float NOT NULL DEFAULT 1,
  `fight_power` float NOT NULL DEFAULT 1,
  `fight_line_pull` float NOT NULL DEFAULT 1,
  `fight_unpredictability` float NOT NULL DEFAULT 0.5,
  `time_modifier` varchar(32) DEFAULT NULL,
  `season_modifier` varchar(32) DEFAULT NULL,
  `special_condition` varchar(128) DEFAULT NULL,
  `trophy_prim_uuid` varchar(36) DEFAULT NULL,
  `texture_uuid` varchar(36) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_rarity` (`rarity_id`),
  CONSTRAINT `fish_species_ibfk_1` FOREIGN KEY (`rarity_id`) REFERENCES `rarity_tiers` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `fish_species` DISABLE KEYS */;
INSERT INTO `fish_species` (`id`, `name`, `rarity_id`, `min_weight`, `max_weight`, `line_tolerance`, `base_points`, `description`, `fight_stamina`, `fight_speed`, `fight_power`, `fight_line_pull`, `fight_unpredictability`, `time_modifier`, `season_modifier`, `special_condition`, `trophy_prim_uuid`, `texture_uuid`, `is_active`, `created_at`) VALUES (1,'Sunfish',1,0.5,2,2.5,3,NULL,15,0.5,0.3,0.3,0.2,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(2,'Bluegill',1,0.5,3,2.5,5,NULL,20,0.8,0.4,0.3,0.3,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(3,'Bullhead Catfish',1,1,5,4,6,NULL,25,0.6,0.6,0.5,0.4,'night',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(4,'Koi',2,3,10,4,18,NULL,40,0.7,0.7,0.6,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(5,'Largemouth Bass',2,2,8,6,15,NULL,45,1,1,0.8,0.6,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(6,'Snapping Turtle',3,10,30,4,45,NULL,70,0.3,1.5,2,0.3,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(7,'Golden Koi',5,8,15,6,400,NULL,90,1.2,1,0.8,0.9,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(8,'Creek Chub',1,0.25,2,4,4,NULL,15,1,0.3,0.2,0.2,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(9,'Rainbow Trout',1,1,6,6,8,NULL,30,1.2,0.5,0.5,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(10,'Brown Trout',2,2,10,6,20,NULL,45,1,0.7,0.7,0.6,'dawn_dusk',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(11,'Smallmouth Bass',2,2,7,10,18,NULL,50,1.2,1,0.8,0.7,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(12,'Walleye',3,3,15,10,50,NULL,65,0.8,1.2,1,0.5,'dawn_dusk',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(13,'Salmon',3,5,25,18,60,NULL,80,1.5,1,1.2,0.6,'any','fall',NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(14,'River Sturgeon',4,20,80,18,150,NULL,95,0.5,1.8,1.5,0.4,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(15,'Ghost Catfish',5,15,40,8,450,NULL,90,1.5,1.3,1.5,0.9,'night',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(16,'Perch',1,0.5,3,15,5,NULL,18,0.6,0.4,0.3,0.3,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(17,'Crappie',1,0.5,4,15,6,NULL,22,0.9,0.5,0.3,0.4,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(18,'Channel Catfish',2,3,20,18,22,NULL,50,0.6,1,0.9,0.5,'night',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(19,'Lake LM Bass',2,3,12,5,20,NULL,50,1.1,1,0.9,0.7,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(20,'Carp',2,5,30,18,14,NULL,60,0.5,0.8,0.8,0.4,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(21,'Northern Pike',3,5,25,25,55,NULL,70,1.3,1.5,1.2,0.7,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(22,'Lake Trout',3,5,30,25,55,NULL,75,0.7,1.3,1,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(23,'Muskie',4,10,50,30,180,NULL,95,1.5,1.5,1.3,0.8,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(24,'Albino Muskie',5,20,60,30,500,NULL,99,1.8,1.8,1.5,0.95,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(25,'Mackerel',1,1,5,20,7,NULL,25,1.2,0.5,0.4,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(26,'Sea Bass',1,2,10,20,10,NULL,30,0.8,0.7,0.6,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(27,'Flounder',2,2,12,25,20,NULL,40,0.4,1,0.8,0.3,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(28,'Red Snapper',2,3,15,25,25,NULL,50,0.8,1,0.9,0.5,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(29,'Yellowfin Tuna',3,15,80,45,75,NULL,85,1.5,1,1.5,0.6,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(30,'Barracuda',3,5,30,45,65,NULL,60,1.8,1.5,1.3,0.8,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(31,'Swordfish',4,50,200,70,200,NULL,95,0.7,1.8,1.8,0.6,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(32,'Hammerhead Shark',4,80,300,70,250,NULL,90,1.5,2,2,0.7,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(33,'Blue Marlin',5,100,500,100,600,NULL,99,1.8,2,2,0.95,'any',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33'),
(34,'Spectral Jellyfish',5,2,5,100,350,NULL,80,2,0.5,0.3,1,'any',NULL,'bioluminescent_tide',NULL,NULL,1,'2026-09-14 18:28:33'),
(35,'Eel',3,2,8,12,40,NULL,55,1,0.8,0.6,0.7,'night',NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:33');
/*!40000 ALTER TABLE `fish_species` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `fish_water_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fish_water_types` (
  `fish_id` int(10) unsigned NOT NULL,
  `water_type_id` int(10) unsigned NOT NULL,
  `catch_weight_override` float DEFAULT NULL,
  PRIMARY KEY (`fish_id`,`water_type_id`),
  KEY `water_type_id` (`water_type_id`),
  CONSTRAINT `fish_water_types_ibfk_1` FOREIGN KEY (`fish_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `fish_water_types_ibfk_2` FOREIGN KEY (`water_type_id`) REFERENCES `water_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `fish_water_types` DISABLE KEYS */;
INSERT INTO `fish_water_types` (`fish_id`, `water_type_id`, `catch_weight_override`) VALUES (1,1,NULL),
(2,1,NULL),
(3,1,NULL),
(4,1,NULL),
(5,1,NULL),
(6,1,NULL),
(7,1,NULL),
(8,2,NULL),
(9,2,NULL),
(10,2,NULL),
(11,2,NULL),
(12,2,NULL),
(13,2,NULL),
(14,2,NULL),
(15,2,NULL),
(16,3,NULL),
(17,3,NULL),
(18,3,NULL),
(19,3,NULL),
(20,3,NULL),
(21,3,NULL),
(22,3,NULL),
(23,3,NULL),
(24,3,NULL),
(25,4,NULL),
(26,4,NULL),
(27,4,NULL),
(28,4,NULL),
(29,4,NULL),
(30,4,NULL),
(31,4,NULL),
(32,4,NULL),
(33,4,NULL),
(34,4,NULL),
(35,2,NULL),
(35,3,NULL);
/*!40000 ALTER TABLE `fish_water_types` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `fishing_spots`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `fishing_spots` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned DEFAULT NULL,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `name` varchar(128) NOT NULL,
  `water_type_id` int(10) unsigned NOT NULL,
  `region_name` varchar(64) DEFAULT NULL,
  `region_x` int(11) DEFAULT NULL,
  `region_y` int(11) DEFAULT NULL,
  `grid_name` varchar(64) DEFAULT NULL,
  `pos_x` float DEFAULT NULL,
  `pos_y` float DEFAULT NULL,
  `pos_z` float DEFAULT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `loot_modifier` float NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_public` tinyint(1) NOT NULL DEFAULT 1,
  `setup_complete` tinyint(1) NOT NULL DEFAULT 0,
  `archived` tinyint(1) NOT NULL DEFAULT 0,
  `archived_at` datetime DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `spot_xp` int(10) unsigned NOT NULL DEFAULT 0,
  `spot_level` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `spot_level_ready` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_water_type` (`water_type_id`),
  KEY `idx_player` (`player_id`),
  KEY `idx_archived` (`archived`),
  CONSTRAINT `fishing_spots_ibfk_1` FOREIGN KEY (`water_type_id`) REFERENCES `water_types` (`id`),
  CONSTRAINT `fk_fishing_spots_player` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `fishing_spots` DISABLE KEYS */;
/*!40000 ALTER TABLE `fishing_spots` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `gather_cooldowns`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `gather_cooldowns` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `bait_id` int(10) unsigned NOT NULL,
  `spot_key` varchar(64) DEFAULT NULL,
  `last_gathered` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cooldown` (`player_id`,`bait_id`,`spot_key`),
  KEY `bait_id` (`bait_id`),
  CONSTRAINT `gather_cooldowns_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `gather_cooldowns_ibfk_2` FOREIGN KEY (`bait_id`) REFERENCES `bait_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `gather_cooldowns` DISABLE KEYS */;
/*!40000 ALTER TABLE `gather_cooldowns` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `grids`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `grids` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `grid_name` varchar(128) NOT NULL,
  `nickname` varchar(128) DEFAULT NULL,
  `hop_gateway` varchar(128) DEFAULT NULL,
  `status` enum('pending','approved','denied') NOT NULL DEFAULT 'pending',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `approved_at` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `grid_name` (`grid_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `grids` DISABLE KEYS */;
INSERT INTO `grids` (`id`, `grid_name`, `nickname`, `hop_gateway`, `status`, `created_at`, `approved_at`, `notes`) VALUES (1,'Tranquillity','Tranquillity',NULL,'approved','2026-09-14 18:28:33','2026-09-14 18:28:33',NULL);
/*!40000 ALTER TABLE `grids` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `hud_exclusion_triggers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `hud_exclusion_triggers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `triggered_uuid` char(36) NOT NULL,
  `blocking_uuid` char(36) DEFAULT NULL,
  `triggered_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_player_uuid` (`player_id`,`triggered_uuid`),
  KEY `idx_when` (`triggered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `hud_exclusion_triggers` DISABLE KEYS */;
/*!40000 ALTER TABLE `hud_exclusion_triggers` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `hud_pair_attempts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `hud_pair_attempts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned DEFAULT NULL,
  `attempted_uuid` char(36) NOT NULL,
  `grid_name` varchar(64) DEFAULT NULL,
  `avatar_name` varchar(128) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `succeeded` tinyint(1) NOT NULL DEFAULT 0,
  `attempted_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_player` (`player_id`,`attempted_at`),
  KEY `idx_uuid` (`attempted_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `hud_pair_attempts` DISABLE KEYS */;
/*!40000 ALTER TABLE `hud_pair_attempts` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `hud_pairing_codes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `hud_pairing_codes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(8) NOT NULL,
  `player_uuid` varchar(36) NOT NULL,
  `grid_name` varchar(64) DEFAULT NULL,
  `player_id` int(10) unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime NOT NULL,
  `claimed` tinyint(1) NOT NULL DEFAULT 0,
  `claimed_at` datetime DEFAULT NULL,
  `issued_token_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `player_id` (`player_id`),
  KEY `idx_code` (`code`),
  KEY `idx_uuid` (`player_uuid`),
  KEY `idx_expires` (`expires_at`),
  CONSTRAINT `hud_pairing_codes_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `hud_pairing_codes` DISABLE KEYS */;
/*!40000 ALTER TABLE `hud_pairing_codes` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `hud_tokens`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `hud_tokens` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `token` varchar(128) NOT NULL,
  `device_name` varchar(64) DEFAULT 'HUD',
  `grid_name` varchar(64) DEFAULT NULL,
  `last_nonce` bigint(20) unsigned NOT NULL DEFAULT 0,
  `issued_at` datetime NOT NULL DEFAULT current_timestamp(),
  `last_used` datetime DEFAULT NULL,
  `last_ip` varchar(45) DEFAULT NULL,
  `callback_url` varchar(512) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `revoked_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `idx_token` (`token`),
  KEY `idx_player` (`player_id`),
  KEY `idx_player_grid` (`player_id`,`grid_name`,`is_active`),
  CONSTRAINT `hud_tokens_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `hud_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `hud_tokens` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `levels`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `levels` (
  `level` int(10) unsigned NOT NULL,
  `xp_required` int(10) unsigned NOT NULL,
  `title` varchar(64) DEFAULT NULL,
  `unlock_notes` text DEFAULT NULL,
  PRIMARY KEY (`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `levels` DISABLE KEYS */;
INSERT INTO `levels` (`level`, `xp_required`, `title`, `unlock_notes`) VALUES (1,0,'Beginner','Pond access, basic rod'),
(2,100,'Novice',NULL),
(3,300,'Apprentice','River access'),
(4,600,NULL,NULL),
(5,1000,'Journeyman','Rod upgrade tier 2, lake access'),
(6,1500,NULL,NULL),
(7,2200,'Skilled Angler',NULL),
(8,3000,NULL,'Rod upgrade tier 3'),
(9,4000,NULL,NULL),
(10,5500,'Expert','Ocean access'),
(11,8000,NULL,NULL),
(12,12000,NULL,'Rod upgrade tier 4'),
(13,18000,NULL,NULL),
(14,26000,'Master Angler',NULL),
(15,38000,NULL,'Rod upgrade tier 5 (max)'),
(16,55000,NULL,NULL),
(17,78000,NULL,NULL),
(18,110000,'Grand Master',NULL),
(19,155000,NULL,NULL),
(20,220000,'Legendary Angler','All content unlocked');
/*!40000 ALTER TABLE `levels` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `line_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `line_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `weight_lb` float NOT NULL,
  `visibility` float NOT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `cost_points` int(10) unsigned NOT NULL DEFAULT 0,
  `description` text DEFAULT NULL,
  `sort_order` int(10) unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `line_types` DISABLE KEYS */;
INSERT INTO `line_types` (`id`, `name`, `weight_lb`, `visibility`, `min_level`, `cost_points`, `description`, `sort_order`, `created_at`) VALUES (1,'Twine',1.5,2,0,0,'Rough twine. Starter line everyone gets. Weaker but also not that hard to see.',0,'2026-09-14 18:28:33'),
(2,'Thin Monofilament',2,1.5,1,50,'Clear thin line. Almost invisible to small fish. Snaps on anything bigger than a sunfish.',1,'2026-09-14 18:28:33'),
(3,'Standard Monofilament',6,3,3,150,'Reliable all-purpose pond and river line.',2,'2026-09-14 18:28:33'),
(4,'Braided Nylon',12,6.5,5,400,'Tough line for medium river and small lake work. Pond fish can see it.',3,'2026-09-14 18:28:33'),
(5,'Heavy Braid',25,14,10,1000,'Big lake line. Visible enough that small fish avoid it entirely.',4,'2026-09-14 18:28:33'),
(6,'Deep Sea Cable',50,30,15,2500,'Thick ocean line for big saltwater fish.',5,'2026-09-14 18:28:33'),
(7,'Titanium Leader',100,70,20,6000,'Premium leader for sharks and marlins. Only monsters will bite this.',6,'2026-09-14 18:28:33');
/*!40000 ALTER TABLE `line_types` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_bait`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_bait` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `bait_id` int(10) unsigned NOT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_bait` (`player_id`,`bait_id`),
  KEY `bait_id` (`bait_id`),
  CONSTRAINT `player_bait_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_bait_ibfk_2` FOREIGN KEY (`bait_id`) REFERENCES `bait_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_bait` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_bait` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_buff_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_buff_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `buff_item_id` int(10) unsigned NOT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_buff` (`player_id`,`buff_item_id`),
  KEY `buff_item_id` (`buff_item_id`),
  CONSTRAINT `player_buff_items_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_buff_items_ibfk_2` FOREIGN KEY (`buff_item_id`) REFERENCES `buff_items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_buff_items` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_buff_items` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_fish`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_fish` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `fish_species_id` int(10) unsigned NOT NULL,
  `weight` float NOT NULL,
  `rarity_id` int(10) unsigned NOT NULL,
  `spot_id` int(10) unsigned DEFAULT NULL,
  `bait_used_id` int(10) unsigned DEFAULT NULL,
  `rod_used_id` int(10) unsigned DEFAULT NULL,
  `caught_at` datetime NOT NULL DEFAULT current_timestamp(),
  `status` enum('held','sold','saved') NOT NULL DEFAULT 'held',
  `sold_at` datetime DEFAULT NULL,
  `points_received` int(10) unsigned DEFAULT NULL,
  `quest_id` int(10) unsigned DEFAULT NULL,
  `physical_copy` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `fish_species_id` (`fish_species_id`),
  KEY `rarity_id` (`rarity_id`),
  KEY `spot_id` (`spot_id`),
  KEY `bait_used_id` (`bait_used_id`),
  KEY `rod_used_id` (`rod_used_id`),
  KEY `idx_player_status` (`player_id`,`status`),
  KEY `idx_player_species` (`player_id`,`fish_species_id`),
  KEY `idx_caught_at` (`caught_at`),
  CONSTRAINT `player_fish_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_fish_ibfk_2` FOREIGN KEY (`fish_species_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `player_fish_ibfk_3` FOREIGN KEY (`rarity_id`) REFERENCES `rarity_tiers` (`id`),
  CONSTRAINT `player_fish_ibfk_4` FOREIGN KEY (`spot_id`) REFERENCES `fishing_spots` (`id`),
  CONSTRAINT `player_fish_ibfk_5` FOREIGN KEY (`bait_used_id`) REFERENCES `bait_types` (`id`),
  CONSTRAINT `player_fish_ibfk_6` FOREIGN KEY (`rod_used_id`) REFERENCES `rod_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_fish` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_fish` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_lines`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_lines` (
  `player_id` int(10) unsigned NOT NULL,
  `line_id` int(10) unsigned NOT NULL,
  `acquired_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`player_id`,`line_id`),
  KEY `line_id` (`line_id`),
  CONSTRAINT `player_lines_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_lines_ibfk_2` FOREIGN KEY (`line_id`) REFERENCES `line_types` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_lines` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_lines` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_quest_progress`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_quest_progress` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_quest_id` int(10) unsigned NOT NULL,
  `requirement_id` int(10) unsigned NOT NULL,
  `current_count` int(10) unsigned NOT NULL DEFAULT 0,
  `is_complete` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_progress` (`player_quest_id`,`requirement_id`),
  KEY `requirement_id` (`requirement_id`),
  CONSTRAINT `player_quest_progress_ibfk_1` FOREIGN KEY (`player_quest_id`) REFERENCES `player_quests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_quest_progress_ibfk_2` FOREIGN KEY (`requirement_id`) REFERENCES `quest_requirements` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_quest_progress` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_quest_progress` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_questions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_questions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned DEFAULT NULL,
  `player_name` varchar(128) DEFAULT NULL,
  `question` text NOT NULL,
  `status` enum('new','answered','dismissed') NOT NULL DEFAULT 'new',
  `admin_reply` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `replied_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `player_id` (`player_id`),
  CONSTRAINT `player_questions_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_questions` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_questions` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_quests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_quests` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `quest_id` int(10) unsigned NOT NULL,
  `status` enum('active','completed','failed','abandoned') NOT NULL DEFAULT 'active',
  `accepted_at` datetime NOT NULL DEFAULT current_timestamp(),
  `completed_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_player_status` (`player_id`,`status`),
  KEY `quest_id` (`quest_id`),
  CONSTRAINT `player_quests_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_quests_ibfk_2` FOREIGN KEY (`quest_id`) REFERENCES `quests` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_quests` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_quests` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_rods`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_rods` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `rod_id` int(10) unsigned NOT NULL,
  `acquired_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_player_rod` (`player_id`,`rod_id`),
  KEY `rod_id` (`rod_id`),
  CONSTRAINT `player_rods_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_rods_ibfk_2` FOREIGN KEY (`rod_id`) REFERENCES `rod_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_rods` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_rods` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_saved_fish`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_saved_fish` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `player_fish_id` int(10) unsigned NOT NULL,
  `note` varchar(255) DEFAULT NULL,
  `saved_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `player_fish_id` (`player_fish_id`),
  KEY `idx_player` (`player_id`),
  CONSTRAINT `player_saved_fish_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE,
  CONSTRAINT `player_saved_fish_ibfk_2` FOREIGN KEY (`player_fish_id`) REFERENCES `player_fish` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_saved_fish` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_saved_fish` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `player_titles`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `player_titles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `title` varchar(64) NOT NULL,
  `source` enum('level','quest','tournament','special') NOT NULL,
  `earned_at` datetime NOT NULL DEFAULT current_timestamp(),
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_player` (`player_id`),
  CONSTRAINT `player_titles_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `player_titles` DISABLE KEYS */;
/*!40000 ALTER TABLE `player_titles` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `players`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `players` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `username` varchar(64) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `display_name` varchar(128) NOT NULL,
  `home_grid` varchar(64) DEFAULT NULL,
  `tutorial_completed` tinyint(1) NOT NULL DEFAULT 0,
  `tutorial_step` int(11) NOT NULL DEFAULT 0,
  `level` int(10) unsigned NOT NULL DEFAULT 1,
  `xp` int(10) unsigned NOT NULL DEFAULT 0,
  `fishing_points` int(10) unsigned NOT NULL DEFAULT 0,
  `equipped_bait_id` int(10) unsigned DEFAULT NULL,
  `equipped_rod_id` int(10) unsigned DEFAULT NULL,
  `equipped_line_id` int(10) unsigned DEFAULT NULL,
  `setup_token` varchar(128) DEFAULT NULL,
  `token_expires` datetime DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `is_banned` tinyint(1) NOT NULL DEFAULT 0,
  `spot_limit_override` int(10) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `last_login` datetime DEFAULT NULL,
  `last_fished` datetime DEFAULT NULL,
  `total_casts` int(10) unsigned NOT NULL DEFAULT 0,
  `total_catches` int(10) unsigned NOT NULL DEFAULT 0,
  `total_points_earned` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_uuid` (`uuid`),
  KEY `idx_username` (`username`),
  KEY `fk_players_equipped_line` (`equipped_line_id`),
  CONSTRAINT `fk_players_equipped_line` FOREIGN KEY (`equipped_line_id`) REFERENCES `line_types` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `players` DISABLE KEYS */;
/*!40000 ALTER TABLE `players` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `prim_callbacks`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `prim_callbacks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `prim_uuid` char(36) NOT NULL,
  `prim_type` varchar(32) NOT NULL,
  `ref_id` int(10) unsigned DEFAULT NULL,
  `callback_url` varchar(512) NOT NULL,
  `region_name` varchar(64) DEFAULT NULL,
  `grid_name` varchar(64) DEFAULT NULL,
  `last_seen` datetime NOT NULL DEFAULT current_timestamp(),
  `registered_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_prim` (`prim_uuid`),
  KEY `idx_type_ref` (`prim_type`,`ref_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `prim_callbacks` DISABLE KEYS */;
/*!40000 ALTER TABLE `prim_callbacks` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `quest_requirements`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `quest_requirements` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `quest_id` int(10) unsigned NOT NULL,
  `fish_species_id` int(10) unsigned DEFAULT NULL,
  `water_type_id` int(10) unsigned DEFAULT NULL,
  `bait_required_id` int(10) unsigned DEFAULT NULL,
  `spot_id` int(10) unsigned DEFAULT NULL,
  `min_weight` float DEFAULT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `min_rarity_id` int(10) unsigned DEFAULT NULL,
  `time_of_day` varchar(32) DEFAULT NULL,
  `description` varchar(256) DEFAULT NULL,
  `track_type` enum('catch','gather','manual') NOT NULL DEFAULT 'catch',
  PRIMARY KEY (`id`),
  KEY `fish_species_id` (`fish_species_id`),
  KEY `water_type_id` (`water_type_id`),
  KEY `bait_required_id` (`bait_required_id`),
  KEY `spot_id` (`spot_id`),
  KEY `idx_quest` (`quest_id`),
  CONSTRAINT `quest_requirements_ibfk_1` FOREIGN KEY (`quest_id`) REFERENCES `quests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `quest_requirements_ibfk_2` FOREIGN KEY (`fish_species_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `quest_requirements_ibfk_3` FOREIGN KEY (`water_type_id`) REFERENCES `water_types` (`id`),
  CONSTRAINT `quest_requirements_ibfk_4` FOREIGN KEY (`bait_required_id`) REFERENCES `bait_types` (`id`),
  CONSTRAINT `quest_requirements_ibfk_5` FOREIGN KEY (`spot_id`) REFERENCES `fishing_spots` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `quest_requirements` DISABLE KEYS */;
INSERT INTO `quest_requirements` (`id`, `quest_id`, `fish_species_id`, `water_type_id`, `bait_required_id`, `spot_id`, `min_weight`, `quantity`, `min_rarity_id`, `time_of_day`, `description`, `track_type`) VALUES (1,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch any fish','catch'),
(2,2,1,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Sunfish','catch'),
(3,2,2,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Bluegill','catch'),
(4,2,5,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Largemouth Bass','catch'),
(5,3,NULL,NULL,9,NULL,NULL,5,NULL,NULL,'Catch 5 fish with Bread Dough','catch'),
(6,4,NULL,NULL,NULL,NULL,3,1,NULL,NULL,'Catch a fish over 3 lbs','catch'),
(7,5,NULL,NULL,NULL,NULL,NULL,50,NULL,NULL,'Gather 50 bait from gather points','catch'),
(8,6,NULL,2,NULL,NULL,NULL,5,NULL,NULL,'Catch 5 fish from a river','catch'),
(9,7,9,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Rainbow Trout','catch'),
(10,7,10,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Brown Trout','catch'),
(11,8,21,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Northern Pike','catch'),
(12,9,20,NULL,7,NULL,NULL,3,NULL,NULL,'Catch 3 Carp with Corn Kernels','catch'),
(13,10,NULL,4,NULL,NULL,NULL,3,NULL,NULL,'Catch 3 ocean fish','catch'),
(14,11,NULL,NULL,NULL,NULL,20,1,NULL,NULL,'Catch a fish over 20 lbs','catch'),
(15,12,1,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Sunfish','catch'),
(16,12,5,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Largemouth Bass','catch'),
(17,12,9,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Rainbow Trout','catch'),
(18,12,11,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Smallmouth Bass','catch'),
(19,12,13,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Salmon','catch'),
(20,12,16,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Perch','catch'),
(21,12,20,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Carp','catch'),
(22,12,21,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Northern Pike','catch'),
(23,12,25,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Mackerel','catch'),
(24,12,26,NULL,NULL,NULL,NULL,1,NULL,NULL,'Catch a Sea Bass','catch'),
(29,17,NULL,NULL,NULL,NULL,NULL,30,NULL,NULL,'Catch 30 fish','catch'),
(30,18,NULL,NULL,NULL,NULL,NULL,5,NULL,NULL,'Catch 5 different species','catch'),
(31,19,NULL,4,NULL,NULL,NULL,1,NULL,NULL,'Catch 1 ocean fish','catch'),
(32,20,NULL,NULL,NULL,NULL,3,10,NULL,NULL,'Catch 10 fish over 3 lbs','catch'),
(33,21,NULL,NULL,NULL,NULL,NULL,5,NULL,NULL,'Catch 5 fish','catch'),
(34,22,NULL,NULL,NULL,NULL,NULL,8,NULL,NULL,'Catch 8 fish','catch'),
(35,22,NULL,2,NULL,NULL,NULL,2,NULL,NULL,'Catch 2 river fish','catch'),
(36,23,NULL,NULL,NULL,NULL,NULL,10,NULL,NULL,'Catch 10 fish','catch'),
(37,23,NULL,3,NULL,NULL,NULL,3,NULL,NULL,'Catch 3 lake fish','catch'),
(38,24,NULL,NULL,NULL,NULL,NULL,12,NULL,NULL,'Catch 12 fish','catch'),
(39,24,NULL,NULL,NULL,NULL,NULL,3,2,NULL,'Catch 3 uncommon+ fish','catch'),
(40,25,NULL,NULL,NULL,NULL,NULL,15,NULL,NULL,'Catch 15 fish','catch'),
(41,25,NULL,4,NULL,NULL,NULL,2,NULL,NULL,'Catch 2 ocean fish','catch'),
(42,26,NULL,NULL,NULL,NULL,2,1,NULL,NULL,'Catch a fish over 2 lbs','catch'),
(43,27,NULL,NULL,NULL,NULL,4,1,NULL,NULL,'Catch a fish over 4 lbs','catch'),
(44,28,NULL,NULL,NULL,NULL,6,1,NULL,NULL,'Catch a fish over 6 lbs','catch'),
(45,29,NULL,NULL,NULL,NULL,10,1,NULL,NULL,'Catch a fish over 10 lbs','catch'),
(46,30,NULL,NULL,NULL,NULL,15,1,NULL,NULL,'Catch a fish over 15 lbs','catch'),
(47,31,NULL,NULL,NULL,NULL,NULL,3,3,NULL,'Catch 3 rare+ fish','catch'),
(48,32,NULL,NULL,NULL,NULL,NULL,4,3,NULL,'Catch 4 rare+ fish','catch'),
(49,33,NULL,NULL,NULL,NULL,NULL,3,4,NULL,'Catch 3 epic+ fish','catch'),
(50,34,NULL,NULL,NULL,NULL,NULL,2,5,NULL,'Catch 2 legendary fish','catch'),
(51,35,NULL,NULL,NULL,NULL,NULL,3,5,NULL,'Catch 3 legendary fish','catch'),
(52,36,NULL,NULL,NULL,NULL,NULL,20,NULL,NULL,'Gather 20 bait','gather'),
(53,37,NULL,NULL,NULL,NULL,NULL,35,NULL,NULL,'Gather 35 bait','gather'),
(54,38,NULL,NULL,NULL,NULL,NULL,50,NULL,NULL,'Gather 50 bait','gather'),
(55,39,NULL,NULL,NULL,NULL,NULL,75,NULL,NULL,'Gather 75 bait','gather'),
(56,40,NULL,NULL,NULL,NULL,NULL,100,NULL,NULL,'Gather 100 bait','gather');
/*!40000 ALTER TABLE `quest_requirements` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `quest_rewards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `quest_rewards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `quest_id` int(10) unsigned NOT NULL,
  `reward_type` enum('points','xp','bait','rod','title','trophy','special','buff_item') NOT NULL,
  `reward_value` int(10) unsigned NOT NULL DEFAULT 0,
  `reward_ref_id` int(10) unsigned DEFAULT NULL,
  `reward_title` varchar(64) DEFAULT NULL,
  `description` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_quest` (`quest_id`),
  CONSTRAINT `quest_rewards_ibfk_1` FOREIGN KEY (`quest_id`) REFERENCES `quests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `quest_rewards` DISABLE KEYS */;
INSERT INTO `quest_rewards` (`id`, `quest_id`, `reward_type`, `reward_value`, `reward_ref_id`, `reward_title`, `description`) VALUES (1,1,'points',50,NULL,NULL,'50 Fishing Points'),
(2,1,'bait',10,1,NULL,'10 Earthworms'),
(3,2,'points',100,NULL,NULL,'100 Fishing Points'),
(4,3,'points',75,NULL,NULL,'75 Fishing Points'),
(5,3,'bait',20,7,NULL,'20 Corn Kernels'),
(6,4,'points',150,NULL,NULL,'150 Fishing Points'),
(7,5,'points',30,NULL,NULL,'30 Fishing Points'),
(8,6,'points',200,NULL,NULL,'200 Fishing Points'),
(9,6,'bait',15,2,NULL,'15 Grasshoppers'),
(10,7,'points',250,NULL,NULL,'250 Fishing Points'),
(11,7,'bait',10,4,NULL,'10 Minnows'),
(12,8,'points',400,NULL,NULL,'400 Fishing Points'),
(13,8,'bait',5,6,NULL,'5 Leeches'),
(14,9,'points',300,NULL,NULL,'300 Fishing Points'),
(15,9,'bait',20,9,NULL,'20 Bread Dough'),
(16,10,'points',500,NULL,NULL,'500 Fishing Points'),
(17,10,'bait',15,8,NULL,'15 Shrimp'),
(18,11,'points',750,NULL,NULL,'750 Fishing Points'),
(19,11,'bait',5,10,NULL,'5 Glow Grubs'),
(20,12,'rod',1,3,NULL,'Graphite Rod'),
(25,17,'points',200,NULL,NULL,'200 Fishing Points'),
(26,17,'buff_item',1,3,NULL,'1x Growth Tonic'),
(27,18,'buff_item',2,4,NULL,'2x Angler\'s Blessing'),
(28,19,'points',300,NULL,NULL,'300 Fishing Points'),
(29,19,'buff_item',2,5,NULL,'2x Treasure Scent'),
(30,20,'buff_item',2,3,NULL,'2x Growth Tonic'),
(31,20,'buff_item',1,4,NULL,'1x Angler\'s Blessing'),
(32,21,'points',50,NULL,NULL,'50 Fishing Points'),
(33,22,'points',80,NULL,NULL,'80 Fishing Points'),
(34,22,'xp',50,NULL,NULL,'50 XP'),
(35,23,'points',120,NULL,NULL,'120 Fishing Points'),
(36,23,'xp',100,NULL,NULL,'100 XP'),
(37,24,'points',180,NULL,NULL,'180 Fishing Points'),
(38,24,'buff_item',1,3,NULL,'1x Growth Tonic'),
(39,25,'points',250,NULL,NULL,'250 Fishing Points'),
(40,25,'buff_item',1,3,NULL,'1x Growth Tonic'),
(41,25,'buff_item',1,4,NULL,'1x Angler\'s Blessing'),
(42,26,'points',50,NULL,NULL,'50 Fishing Points'),
(43,27,'points',80,NULL,NULL,'80 Fishing Points'),
(44,28,'points',120,NULL,NULL,'120 Fishing Points'),
(45,28,'buff_item',1,5,NULL,'1x Treasure Scent'),
(46,29,'points',180,NULL,NULL,'180 Fishing Points'),
(47,29,'buff_item',1,5,NULL,'1x Treasure Scent'),
(48,30,'points',250,NULL,NULL,'250 Fishing Points'),
(49,30,'buff_item',2,5,NULL,'2x Treasure Scent'),
(50,31,'buff_item',1,3,NULL,'1x Growth Tonic'),
(51,32,'points',100,NULL,NULL,'100 Fishing Points'),
(52,32,'buff_item',1,3,NULL,'1x Growth Tonic'),
(53,33,'points',150,NULL,NULL,'150 Fishing Points'),
(54,33,'buff_item',2,3,NULL,'2x Growth Tonic'),
(55,34,'points',200,NULL,NULL,'200 Fishing Points'),
(56,34,'buff_item',1,2,NULL,'1x Lucky Lure Oil'),
(57,35,'points',300,NULL,NULL,'300 Fishing Points'),
(58,35,'buff_item',1,2,NULL,'1x Lucky Lure Oil'),
(59,35,'buff_item',1,4,NULL,'1x Angler\'s Blessing'),
(60,36,'buff_item',1,4,NULL,'1x Angler\'s Blessing'),
(61,37,'points',80,NULL,NULL,'80 Fishing Points'),
(62,37,'buff_item',1,4,NULL,'1x Angler\'s Blessing'),
(63,38,'points',120,NULL,NULL,'120 Fishing Points'),
(64,38,'buff_item',2,4,NULL,'2x Angler\'s Blessing'),
(65,39,'points',180,NULL,NULL,'180 Fishing Points'),
(66,39,'buff_item',1,7,NULL,'1x Bait Saver'),
(67,40,'points',250,NULL,NULL,'250 Fishing Points'),
(68,40,'buff_item',1,7,NULL,'1x Bait Saver'),
(69,40,'buff_item',1,4,NULL,'1x Angler\'s Blessing');
/*!40000 ALTER TABLE `quest_rewards` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `quests`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `quests` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `description` text NOT NULL,
  `quest_type` enum('collection','size','multi_species','rare_catch','timed','seasonal') NOT NULL,
  `chain_id` int(10) unsigned DEFAULT NULL,
  `chain_order` int(10) unsigned DEFAULT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `is_repeatable` tinyint(1) NOT NULL DEFAULT 0,
  `repeat_type` enum('none','daily','weekly') NOT NULL DEFAULT 'none',
  `repeat_cooldown` int(10) unsigned DEFAULT NULL,
  `quest_group` varchar(32) DEFAULT NULL,
  `quest_tier` tinyint(3) unsigned DEFAULT NULL,
  `time_limit` int(10) unsigned DEFAULT NULL,
  `season` varchar(32) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_chain` (`chain_id`,`chain_order`),
  KEY `idx_quest_group` (`quest_group`,`quest_tier`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `quests` DISABLE KEYS */;
INSERT INTO `quests` (`id`, `title`, `description`, `quest_type`, `chain_id`, `chain_order`, `min_level`, `is_repeatable`, `repeat_type`, `repeat_cooldown`, `quest_group`, `quest_tier`, `time_limit`, `season`, `is_active`, `created_at`) VALUES (1,'First Catch','Catch your very first fish! Any species, any size — just get one on the line.','collection',NULL,NULL,1,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(2,'Pond Sampler','Catch 3 different species from a pond. Try different bait to find what works!','multi_species',NULL,NULL,1,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(3,'Bread Winner','Catch 5 fish using Bread Dough as bait. Koi and Bluegill love it!','collection',NULL,NULL,1,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(4,'The Big One','Land a fish weighing over 3 pounds. Try using Minnows on a Largemouth Bass!','size',NULL,NULL,1,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(5,'Worm Farmer','Gather 50 pieces of bait from gathering points around the world. Sit down and search!','collection',NULL,NULL,1,1,'none',24,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(6,'River Runner','Head to a river and catch 5 fish. Rivers unlock at Level 3. Grasshoppers are great for trout!','collection',NULL,NULL,3,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(7,'Trout Tracker','Track down both species of trout. Rainbow Trout love Grasshoppers, Brown Trout prefer Minnows.','multi_species',NULL,NULL,3,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(8,'Lake Legend','Northern Pike are ambush predators lurking in the lake. Use Minnows or Cut Bait to lure one out.','collection',NULL,NULL,5,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(9,'Carp Whisperer','Carp are stubborn bottom feeders. Use Corn Kernels to catch 3 of them from a lake.','collection',NULL,NULL,5,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(10,'Deep Sea Debut','The ocean awaits! Catch 3 fish from ocean waters. You\'ll need Shrimp or Cut Bait and a strong line.','collection',NULL,NULL,10,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(11,'Monster Hunter','Land a true monster — a fish weighing over 20 pounds. Try deep lake or ocean fish with heavy tackle.','size',NULL,NULL,10,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(12,'The Angler\'s Rod','Prove your skill by catching 10 different species across all water types. A master angler deserves a master\'s tool.','multi_species',NULL,NULL,8,0,'none',NULL,NULL,NULL,NULL,NULL,1,'2026-09-14 18:28:34'),
(17,'Weekly Angler','Catch 30 fish this week.','collection',NULL,NULL,1,1,'weekly',168,'weekly_angler',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(18,'Species Sampler','Catch 5 different species this week.','multi_species',NULL,NULL,3,1,'weekly',168,'species_sampler',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(19,'Deep Sea Challenge','Catch any fish from the ocean this week.','collection',NULL,NULL,10,1,'weekly',168,'deep_sea',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(20,'Heavy Hauler','Catch 10 fish weighing over 3 lbs this week.','size',NULL,NULL,5,1,'weekly',168,'heavy_hauler',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(21,'Daily Catch','Catch 5 fish today. Any species, any water.','collection',NULL,NULL,1,1,'daily',24,'daily_catch',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(22,'Daily Catch II','Catch 8 fish today, at least 2 from a river.','collection',NULL,NULL,3,1,'daily',24,'daily_catch',2,NULL,NULL,1,'2026-09-14 18:28:34'),
(23,'Daily Catch III','Catch 10 fish today, at least 3 from a lake.','collection',NULL,NULL,5,1,'daily',24,'daily_catch',3,NULL,NULL,1,'2026-09-14 18:28:34'),
(24,'Daily Catch IV','Catch 12 fish today, at least 3 uncommon or better.','collection',NULL,NULL,8,1,'daily',24,'daily_catch',4,NULL,NULL,1,'2026-09-14 18:28:34'),
(25,'Daily Catch V','Catch 15 fish today, at least 2 from the ocean.','collection',NULL,NULL,10,1,'daily',24,'daily_catch',5,NULL,NULL,1,'2026-09-14 18:28:34'),
(26,'Big Fish Day','Catch a fish weighing over 2 lbs.','size',NULL,NULL,1,1,'daily',24,'big_fish',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(27,'Bigger Fish Day','Catch a fish weighing over 4 lbs.','size',NULL,NULL,3,1,'daily',24,'big_fish',2,NULL,NULL,1,'2026-09-14 18:28:34'),
(28,'Huge Fish Day','Catch a fish weighing over 6 lbs.','size',NULL,NULL,5,1,'daily',24,'big_fish',3,NULL,NULL,1,'2026-09-14 18:28:34'),
(29,'Massive Fish Day','Catch a fish weighing over 10 lbs.','size',NULL,NULL,8,1,'daily',24,'big_fish',4,NULL,NULL,1,'2026-09-14 18:28:34'),
(30,'Legendary Fish Day','Catch a fish weighing over 15 lbs.','size',NULL,NULL,10,1,'daily',24,'big_fish',5,NULL,NULL,1,'2026-09-14 18:28:34'),
(31,'Rare Haul','Catch 3 rare or better fish today.','rare_catch',NULL,NULL,4,1,'daily',24,'rare_haul',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(32,'Rarer Haul','Catch 4 rare or better fish today.','rare_catch',NULL,NULL,6,1,'daily',24,'rare_haul',2,NULL,NULL,1,'2026-09-14 18:28:34'),
(33,'Exceptional Haul','Catch 3 epic or better fish today.','rare_catch',NULL,NULL,8,1,'daily',24,'rare_haul',3,NULL,NULL,1,'2026-09-14 18:28:34'),
(34,'Legendary Haul','Catch 2 legendary fish today.','rare_catch',NULL,NULL,10,1,'daily',24,'rare_haul',4,NULL,NULL,1,'2026-09-14 18:28:34'),
(35,'Mythic Haul','Catch 3 legendary fish today.','rare_catch',NULL,NULL,12,1,'daily',24,'rare_haul',5,NULL,NULL,1,'2026-09-14 18:28:34'),
(36,'Bait Collector','Gather 20 pieces of bait today.','collection',NULL,NULL,2,1,'daily',24,'bait_collector',1,NULL,NULL,1,'2026-09-14 18:28:34'),
(37,'Bait Hoarder','Gather 35 pieces of bait today.','collection',NULL,NULL,4,1,'daily',24,'bait_collector',2,NULL,NULL,1,'2026-09-14 18:28:34'),
(38,'Bait Fanatic','Gather 50 pieces of bait today.','collection',NULL,NULL,6,1,'daily',24,'bait_collector',3,NULL,NULL,1,'2026-09-14 18:28:34'),
(39,'Bait Obsessed','Gather 75 pieces of bait today.','collection',NULL,NULL,8,1,'daily',24,'bait_collector',4,NULL,NULL,1,'2026-09-14 18:28:34'),
(40,'Bait Glutton','Gather 100 pieces of bait today.','collection',NULL,NULL,10,1,'daily',24,'bait_collector',5,NULL,NULL,1,'2026-09-14 18:28:34');
/*!40000 ALTER TABLE `quests` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `rarity_tiers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `rarity_tiers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `color_hex` varchar(7) NOT NULL DEFAULT '#FFFFFF',
  `base_xp` int(10) unsigned NOT NULL DEFAULT 0,
  `point_multiplier` float NOT NULL DEFAULT 1,
  `catch_weight` float NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `rarity_tiers` DISABLE KEYS */;
INSERT INTO `rarity_tiers` (`id`, `name`, `color_hex`, `base_xp`, `point_multiplier`, `catch_weight`) VALUES (1,'common','#9D9D9D',8,1,50),
(2,'uncommon','#1EFF00',20,1.5,25),
(3,'rare','#0070FF',55,2.5,10),
(4,'epic','#A335EE',150,5,3),
(5,'legendary','#FF8000',500,15,0.5);
/*!40000 ALTER TABLE `rarity_tiers` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `rod_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `rod_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` text DEFAULT NULL,
  `tier` int(10) unsigned NOT NULL DEFAULT 1,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `cast_range` float NOT NULL DEFAULT 10,
  `reel_speed` float NOT NULL DEFAULT 1,
  `tension_buffer` float NOT NULL DEFAULT 1,
  `line_strength` float NOT NULL DEFAULT 100,
  `cost` int(10) unsigned NOT NULL DEFAULT 0,
  `prim_uuid` varchar(36) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `rod_types` DISABLE KEYS */;
INSERT INTO `rod_types` (`id`, `name`, `description`, `tier`, `min_level`, `cast_range`, `reel_speed`, `tension_buffer`, `line_strength`, `cost`, `prim_uuid`, `is_active`, `created_at`) VALUES (1,'Bamboo Rod',NULL,1,1,10,1,1,100,0,NULL,1,'2026-09-14 18:28:33'),
(2,'Fiberglass Rod',NULL,2,5,15,1.2,1.1,120,200,NULL,1,'2026-09-14 18:28:33'),
(3,'Graphite Rod',NULL,3,8,20,1.4,1.2,150,500,NULL,1,'2026-09-14 18:28:33'),
(4,'Carbon Fiber Rod',NULL,4,12,25,1.6,1.4,200,1200,NULL,1,'2026-09-14 18:28:33'),
(5,'Mastercraft Rod',NULL,5,15,30,2,1.7,275,3000,NULL,1,'2026-09-14 18:28:33');
/*!40000 ALTER TABLE `rod_types` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `sell_transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `sell_transactions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `fish_count` int(10) unsigned NOT NULL,
  `total_points` int(10) unsigned NOT NULL,
  `sold_at` datetime NOT NULL DEFAULT current_timestamp(),
  `details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`details`)),
  PRIMARY KEY (`id`),
  KEY `idx_player` (`player_id`),
  CONSTRAINT `sell_transactions_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `sell_transactions` DISABLE KEYS */;
/*!40000 ALTER TABLE `sell_transactions` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `shop_listings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shop_listings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `shop_id` int(10) unsigned NOT NULL,
  `item_type` enum('bait','rod','buff') NOT NULL DEFAULT 'bait',
  `item_id` int(10) unsigned NOT NULL,
  `stock` int(11) NOT NULL DEFAULT 25,
  `max_stock` int(11) NOT NULL DEFAULT 25,
  `price_modifier` float NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `last_restock` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_item` (`shop_id`,`item_type`,`item_id`),
  CONSTRAINT `shop_listings_ibfk_1` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `shop_listings` DISABLE KEYS */;
/*!40000 ALTER TABLE `shop_listings` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `shop_transactions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shop_transactions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned NOT NULL,
  `item_type` enum('bait','rod','cosmetic','special') NOT NULL,
  `item_ref_id` int(10) unsigned NOT NULL,
  `quantity` int(10) unsigned NOT NULL DEFAULT 1,
  `points_spent` int(10) unsigned NOT NULL,
  `purchased_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_player` (`player_id`),
  KEY `idx_date` (`purchased_at`),
  CONSTRAINT `shop_transactions_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `shop_transactions` DISABLE KEYS */;
/*!40000 ALTER TABLE `shop_transactions` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `shops`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shops` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `player_id` int(10) unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `region_name` varchar(64) DEFAULT NULL,
  `grid_name` varchar(64) DEFAULT NULL,
  `region_x` int(11) DEFAULT NULL,
  `region_y` int(11) DEFAULT NULL,
  `pos_x` float DEFAULT 0,
  `pos_y` float DEFAULT 0,
  `pos_z` float DEFAULT 0,
  `is_system` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `player_id` (`player_id`),
  CONSTRAINT `shops_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `shops` DISABLE KEYS */;
/*!40000 ALTER TABLE `shops` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `spot_buffs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `spot_buffs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `spot_id` int(10) unsigned NOT NULL,
  `buff_type` varchar(32) NOT NULL,
  `buff_value` float NOT NULL DEFAULT 0.25,
  `activated_by` int(10) unsigned DEFAULT NULL,
  `activated_at` datetime NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `activated_by` (`activated_by`),
  KEY `idx_spot_active` (`spot_id`,`expires_at`),
  CONSTRAINT `spot_buffs_ibfk_1` FOREIGN KEY (`spot_id`) REFERENCES `fishing_spots` (`id`) ON DELETE CASCADE,
  CONSTRAINT `spot_buffs_ibfk_2` FOREIGN KEY (`activated_by`) REFERENCES `players` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `spot_buffs` DISABLE KEYS */;
/*!40000 ALTER TABLE `spot_buffs` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `spot_junk_items`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `spot_junk_items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `spot_id` int(10) unsigned NOT NULL,
  `item_name` varchar(128) NOT NULL,
  `rarity_weight` float NOT NULL DEFAULT 1,
  `rarity_label` varchar(16) NOT NULL DEFAULT 'common',
  `added_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_spot` (`spot_id`),
  CONSTRAINT `spot_junk_items_ibfk_1` FOREIGN KEY (`spot_id`) REFERENCES `fishing_spots` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `spot_junk_items` DISABLE KEYS */;
/*!40000 ALTER TABLE `spot_junk_items` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `spot_xp_daily`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `spot_xp_daily` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `spot_id` int(10) unsigned NOT NULL,
  `player_id` int(10) unsigned NOT NULL,
  `log_date` date NOT NULL,
  `fish_count` smallint(5) unsigned NOT NULL DEFAULT 0,
  `xp_given` smallint(5) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_spot_player_date` (`spot_id`,`player_id`,`log_date`),
  KEY `idx_spot_date` (`spot_id`,`log_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `spot_xp_daily` DISABLE KEYS */;
/*!40000 ALTER TABLE `spot_xp_daily` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `tournament_entries`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `tournament_entries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tournament_id` int(10) unsigned NOT NULL,
  `player_id` int(10) unsigned NOT NULL,
  `score` float NOT NULL DEFAULT 0,
  `best_catch_id` int(10) unsigned DEFAULT NULL,
  `total_catches` int(10) unsigned NOT NULL DEFAULT 0,
  `last_updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_entry` (`tournament_id`,`player_id`),
  KEY `player_id` (`player_id`),
  KEY `idx_score` (`tournament_id`,`score` DESC),
  CONSTRAINT `tournament_entries_ibfk_1` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `tournament_entries_ibfk_2` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `tournament_entries` DISABLE KEYS */;
/*!40000 ALTER TABLE `tournament_entries` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `tournament_rewards`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `tournament_rewards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tournament_id` int(10) unsigned NOT NULL,
  `placement` int(10) unsigned NOT NULL,
  `reward_type` enum('points','xp','bait','rod','title','trophy','special') NOT NULL,
  `reward_value` int(10) unsigned NOT NULL DEFAULT 0,
  `reward_ref_id` int(10) unsigned DEFAULT NULL,
  `reward_title` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tournament` (`tournament_id`),
  CONSTRAINT `tournament_rewards_ibfk_1` FOREIGN KEY (`tournament_id`) REFERENCES `tournaments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `tournament_rewards` DISABLE KEYS */;
/*!40000 ALTER TABLE `tournament_rewards` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `tournaments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `tournaments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `scoring_type` enum('biggest_single','total_weight','most_catches','rarest_catch') NOT NULL,
  `target_species_id` int(10) unsigned DEFAULT NULL,
  `target_water_id` int(10) unsigned DEFAULT NULL,
  `starts_at` datetime NOT NULL,
  `ends_at` datetime NOT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `target_species_id` (`target_species_id`),
  KEY `target_water_id` (`target_water_id`),
  CONSTRAINT `tournaments_ibfk_1` FOREIGN KEY (`target_species_id`) REFERENCES `fish_species` (`id`),
  CONSTRAINT `tournaments_ibfk_2` FOREIGN KEY (`target_water_id`) REFERENCES `water_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `tournaments` DISABLE KEYS */;
/*!40000 ALTER TABLE `tournaments` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `water_types`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `water_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `description` text DEFAULT NULL,
  `min_level` int(10) unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `water_types` DISABLE KEYS */;
INSERT INTO `water_types` (`id`, `name`, `description`, `min_level`) VALUES (1,'pond','Calm shallow waters. Ideal for beginners.',1),
(2,'river','Flowing currents with stronger fish.',3),
(3,'lake','Deep open water with wide variety.',5),
(4,'ocean','Vast saltwater. The biggest catches await.',10);
/*!40000 ALTER TABLE `water_types` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `web_sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `web_sessions` (
  `id` varchar(128) NOT NULL,
  `player_id` int(10) unsigned NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_player` (`player_id`),
  KEY `idx_expires` (`expires_at`),
  CONSTRAINT `web_sessions_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `web_sessions` DISABLE KEYS */;
/*!40000 ALTER TABLE `web_sessions` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
DROP TABLE IF EXISTS `world_events`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `world_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_key` varchar(64) NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `starts_at` datetime DEFAULT NULL,
  `ends_at` datetime DEFAULT NULL,
  `auto_trigger` tinyint(1) NOT NULL DEFAULT 0,
  `trigger_chance` float DEFAULT NULL,
  `last_triggered` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `event_key` (`event_key`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
/*!40000 ALTER TABLE `world_events` DISABLE KEYS */;
INSERT INTO `world_events` (`id`, `event_key`, `name`, `description`, `is_active`, `starts_at`, `ends_at`, `auto_trigger`, `trigger_chance`, `last_triggered`) VALUES (1,'bioluminescent_tide','Bioluminescent Tide','The ocean glows with an eerie light. Strange creatures stir beneath the waves.',0,NULL,NULL,1,0.05,NULL);
/*!40000 ALTER TABLE `world_events` ENABLE KEYS */;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;


SET FOREIGN_KEY_CHECKS = 1;
